steps:
  - label: Geneve security serverless quality gate
    env:
      TEST_SCHEMA_URI: ./etc/ecs-v8.11.0.tar.gz
    command:
      - python3 -m pip install -r requirements.txt
      - ./scripts/test-stacks.sh --online -v --queries custom
