name: Build and test

on:
  push:
  pull_request:

env:
  TEST_SCHEMA_URI: "https://github.com/elastic/ecs/archive/refs/tags/v8.1.0.tar.gz"
  TEST_DETECTION_RULES_URI: "https://github.com/elastic/detection-rules/archive/refs/tags/v8.1.0.tar.gz"
  TEST_VERBOSITY: 2

jobs:
  build-test-publish:
    name: 🐍 Build, test and publish 🐍
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: make prereq

    - name: Lint code
      run: make lint

    - name: Test units
      run: make tests

    - name: Build package
      run: make pkg_build

    - name: Install package
      run: make pkg_install

    - name: Try package
      run: make pkg_try

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository != 'elastic/geneve'
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        print_hash: true
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository == 'elastic/geneve'
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true
